#! /bin/sh
### BEGIN INIT INFO
# Provides:          aController 
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The Aquarium Controller Daemon 
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/home/jims/src/controller

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

case "$1" in
  start)
    log_begin_msg "Starting the aquarium controller"
    /home/jims/src/controller/controller.py &
    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping the aquarium controller"
    killproc /home/jims/src/controller/controller.py
    X=`ps aux | grep 'controller.py' | grep 'python' |  grep -v grep`
    X=`echo $X | awk {'print $2'}`
    if [ $X ] 
        then
            kill -2 $X
    fi 
    log_end_msg $?
    exit 0
    ;;
  restart) log_daemon_msg "Restarting the aqarium controller" "aController" 
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/aController {start|stop|restart}"
    exit 1
    ;;
esac
